-- Stage 01: Smart Attendance (QR + BLE Hybrid)
-- Target: Supabase PostgreSQL

BEGIN;

-- Core settings for attendance engine
CREATE TABLE IF NOT EXISTS public.attendance_settings (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  qr_ttl_seconds INTEGER NOT NULL DEFAULT 45,
  proximity_required BOOLEAN NOT NULL DEFAULT true,
  min_ble_rssi INTEGER NOT NULL DEFAULT -72,
  max_clock_skew_seconds INTEGER NOT NULL DEFAULT 90,
  allow_offline_buffer BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT attendance_settings_singleton CHECK (id = 1)
);

INSERT INTO public.attendance_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- QR broadcast sessions generated by teacher/admin device
CREATE TABLE IF NOT EXISTS public.attendance_qr_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope_type TEXT NOT NULL CHECK (scope_type IN ('student', 'course', 'batch', 'branch')),
  scope_student_id UUID,
  scope_course_id BIGINT,
  scope_batch_id BIGINT,
  scope_branch_id BIGINT,
  starts_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  qr_nonce TEXT NOT NULL,
  qr_payload_hash TEXT NOT NULL,
  created_by UUID,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (expires_at > starts_at)
);

CREATE INDEX IF NOT EXISTS idx_attendance_qr_sessions_active_time
  ON public.attendance_qr_sessions (is_active, starts_at, expires_at);

-- BLE proximity validations between teacher and student devices
CREATE TABLE IF NOT EXISTS public.attendance_ble_events (
  id BIGSERIAL PRIMARY KEY,
  qr_session_id UUID REFERENCES public.attendance_qr_sessions(id) ON DELETE CASCADE,
  teacher_device_id TEXT NOT NULL,
  student_device_id TEXT NOT NULL,
  student_id UUID,
  rssi INTEGER,
  estimated_distance_m NUMERIC(6,2),
  captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_valid BOOLEAN NOT NULL DEFAULT false,
  reason TEXT
);

CREATE INDEX IF NOT EXISTS idx_attendance_ble_events_session_student
  ON public.attendance_ble_events (qr_session_id, student_id, captured_at DESC);

-- Final attendance events (accepted/rejected) with anti-fraud metadata
CREATE TABLE IF NOT EXISTS public.attendance_events (
  id BIGSERIAL PRIMARY KEY,
  qr_session_id UUID REFERENCES public.attendance_qr_sessions(id) ON DELETE SET NULL,
  student_id UUID NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('qr', 'ble', 'hybrid')),
  status TEXT NOT NULL CHECK (status IN ('present', 'rejected', 'pending_review')),
  marked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  teacher_device_id TEXT,
  student_device_id TEXT,
  ble_rssi INTEGER,
  estimated_distance_m NUMERIC(6,2),
  confidence_score NUMERIC(5,2) NOT NULL DEFAULT 0,
  rejection_reason TEXT,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_attendance_events_student_time
  ON public.attendance_events (student_id, marked_at DESC);

CREATE INDEX IF NOT EXISTS idx_attendance_events_session
  ON public.attendance_events (qr_session_id, marked_at DESC);

-- Optional daily consolidation view
CREATE OR REPLACE VIEW public.v_attendance_daily AS
SELECT
  student_id,
  date_trunc('day', marked_at) AS attendance_day,
  COUNT(*) FILTER (WHERE status = 'present') AS present_count,
  COUNT(*) FILTER (WHERE status = 'rejected') AS rejected_count,
  MAX(confidence_score) AS max_confidence
FROM public.attendance_events
GROUP BY student_id, date_trunc('day', marked_at);

COMMIT;
